INSERT INTO "AnalisisRisikoPekerjaan" (pekerjaan, "skorRisiko", "kategoriRisiko", "createdAt", "updatedAt") VALUES
('PNS', 10, 'Sangat Rendah', NOW(), NOW()),
('TNI/POLRI', 15, 'Sangat Rendah', NOW(), NOW()),
('Pegawai BUMN', 15, 'Sangat Rendah', NOW(), NOW()),
('Guru/Dosen', 20, 'Rendah', NOW(), NOW()),
('Tenaga Medis', 20, 'Rendah', NOW(), NOW()),
('Pegawai Bank', 20, 'Rendah', NOW(), NOW()),
('Karyawan Swasta Tetap', 25, 'Rendah', NOW(), NOW()),
('Karyawan Kontrak', 40, 'Sedang', NOW(), NOW()),
('Pegawai Honorer', 50, 'Sedang', NOW(), NOW()),
('Profesional', 30, 'Rendah', NOW(), NOW()),
('Sales/Marketing', 45, 'Sedang', NOW(), NOW()),
('Wirausaha/Pengusaha/UMKM/Pedagang', 50, 'Sedang', NOW(), NOW()),
('Petani/Pekebun/Peternak', 60, 'Tinggi', NOW(), NOW()),
('Nelayan', 65, 'Tinggi', NOW(), NOW()),
('Buruh Harian', 70, 'Sangat Tinggi', NOW(), NOW()),
('Buruh Pabrik', 45, 'Sedang', NOW(), NOW()),
('Tukang Bangunan/Teknisi/Mekanik', 45, 'Sedang', NOW(), NOW()),
('Sopir', 45, 'Sedang', NOW(), NOW()),
('Driver Ojol', 65, 'Tinggi', NOW(), NOW()),
('Kurir', 50, 'Sedang', NOW(), NOW()),
('Satpam', 35, 'Rendah', NOW(), NOW()),
('Cleaning Service', 50, 'Sedang', NOW(), NOW()),
('ART', 65, 'Tinggi', NOW(), NOW()),
('Freelance', 70, 'Tinggi', NOW(), NOW()),
('Pensiunan', 30, 'Rendah', NOW(), NOW()),
('Mahasiswa', 90, 'Sangat Tinggi', NOW(), NOW()),
('Belum Bekerja', 95, 'Sangat Tinggi', NOW(), NOW())
ON CONFLICT (pekerjaan) DO NOTHING;
